_:

[
  "bufbuild/buf/buf"
  "cockroachdb/tap/cockroach"
  "hashicorp/tap/vault"
  "gh"
  "zsh-completions"
  "felixkratz/formulae/sketchybar"
  "koekeishiya/formulae/yabai"
  "koekeishiya/formulae/skhd"
  "gpg2"
  "gnupg"
  "pinentry-mac"
  "uv"
  "pulumi/tap/pulumi"
  "age"
  "helm@3"
  "make"
]
